### ISSUE TITLE
Two rpc servers configure the same address but one successfully start, the other failed

### ISSUE THREAD

**Issue by Lady-Summer** [tikv/grpc-rs#598]
## Problem Description
My project has two different services but with the same `grpc-rs` dependency. However, one can start normally and the other failed; 
The exception message is simple:
`[1]    11810 segmentation fault  cargo run --manifest-path src/worker/Cargo.toml`

When I debug deeply, I found a strange phenomenon: 

This screenshot is for the normally started service, you can see on the top left, the `parsed_addr` variable is equal to `addr`, seemingly.
<img width="1771" alt="image" src="https://user-images.githubusercontent.com/68991790/200738745-f417d915-9406-49e9-a9b6-549ed78027a6.png">

This screenshot is for the failed service, you can see on the top left, the `parsed_addr` variable is an unexpected value. 
<img width="1773" alt="image" src="https://user-images.githubusercontent.com/68991790/200739024-f16f61b0-3e25-44f4-b3f3-45cd39a00241.png">

### Normally start service grpc binding code
```rust
    let mut grpc_server = grpcio::ServerBuilder::new(sync::Arc::new(grpcio::Environment::new(10)))
        .register_service(service)
        .bind("0.0.0.0", config.port as u16)
        .build()
        .expect("grpc server create failed");
    grpc_server.start();
```

### Failed start service grpc binding code
```rust
    let grpc_server = grpcio::ServerBuilder::new(sync::Arc::new(grpcio::Environment::new(10)))
        .register_service(service)
        .bind("0.0.0.0", config.port as u16)
        .build();

    if grpc_server.is_err() {
        panic!("{:?}", grpc_server.unwrap_err())
    }

    let mut unwrap_server = grpc_server.expect("grpc server start failed");
    unwrap_server.start();
```

You can see their binding configurations are the same;

## Dependencies
The two projects dependencies are the followings

### Normally start service dependencies
```toml
[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "signal"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
common = { path = "../common" }
proto = { path = "../proto", features = ["coordinator", "worker"] }
serde_json = "1.0.59"

grpcio = "0.10.3"
protobuf = "2.27.1"
rocksdb = { version = "0.19.0", features=["lz4"] }
```

### Failed start service dependencies
```toml
[dependencies]
common = { path = "../common" }
stream = { path = "../stream" }
proto = { path = "../proto", features = ["worker"] }
protobuf = "2.27.1"
grpcio = "0.10.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "signal", "macros"] }
log = "0.4"
serde_json = "1.0.59"
env_logger = "0.9.0"
```

### The common module dependencies
```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
regex = "1"
bytes = "1.1.0"
chrono = "0.4"
proto = { path = "../proto", features = ["proto-common", "worker"] }
serde_json = "1.0.59"
grpcio = "0.10.3"
log = "0.4"
protobuf = "2.27.1"
rdkafka = "0.29.0"
futures-executor = "0.3"

[dev-dependencies]
common = { path = "../common" }
tokio = { version = "1", features = ["test-util"] }
```

### The proto module dependencies
```toml
[dependencies]
grpcio = "0.10.3"
protobuf = "2.27.1"
```

### The stream module dependencies
```toml
[dependencies]
common = { path = "../common" }
chrono = "0.4"
tokio = { version = "1", features = ["rt"] }
proto = { path = "../proto", features = ["worker"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
crossbeam-channel = "0.5"
v8 = "0.54.0"
protobuf = "2.27.1"

[dev-dependencies]
tokio = { version = "1", features = ["test-util"] }
stream = { path = "../stream" }
```

## Expected behavior
I think for the same binding configuration, the `parsed_addr` should be expected to be equal to `addr`.

## System information
* Computer Version: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
* CPU architecture: 2 GHz Quad-Core Intel Core i5
* Distribution and kernel version: macOS Monterey, version 12.0.1

## Another context
I use Visual Studio Code for debug, with latest CodeLLDB and rust-analysor extensions
